apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-container
        image: bsumanji/webapp-backend
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  selector:
    app: frontend-app
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 4000
    
