---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    env: nginx-dep
    type: frontend
spec:
  selector:
    matchLabels:
      env: nginxdep
  replicas: 3
  template:
    metadata:
      name: nginx-deployment   # this mandatorily dont have to match with Deployment.metadata.labels
      labels:
        env: nginxdep
    spec:
      containers:
        - image: nginx:1.14
          name: nginx-container
