apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:          # not mandatory.
      maxUnavailable: 1  
      maxSurge: 1   
  selector:
    matchLabels:
      app: nginx-rolling
  template:
    metadata:
      labels:
        app: nginx-rolling
    spec:
      containers:
        - name: frontend
          image: nginx:1.7.1

