---
  apiVersion: v1
  kind: Pod
  metadata:
    #this is name that is assigned to pod when created
    name: nginx-pod
    labels:
      app: nginx
      tier: frontend
  spec:
    containers:
      - name: nginx-container
        image: nginx

